import { lazy, Suspense, useMemo, useState } from 'react'
import { CircleDollarSign, Download, Edit3, Landmark, Plus, ReceiptText, Search, Trash2, WalletCards } from 'lucide-react'
import { useLifeStore } from '../../store/useLifeStore'
import { calculateLoan } from '../../utils/calculations'
import { shortDate, todayISO } from '../../utils/core'
import { downloadFile, toCSV } from '../../utils/fileUtils'
import { currency } from '../../utils/numberFormatters'
import { localizeFinanceCategory, localizeSavingsTitle } from '../../utils/localization'
import { Badge, Button, EmptyState, Field, IconButton, Input, Modal, Progress, RingProgress, Select } from '../ui/primitives'
import { Widget } from '../dashboard/Widget'
import type { Transaction, TransactionType } from '../../types'

function useFinanceCopy() {
  const language = useLifeStore(state => state.settings.language)
  return { language, l: (french: string, english: string) => language === 'en' ? english : french }
}
const LoanYearlyChart = lazy(() => import('./FinanceChartModules').then(module => ({ default: module.LoanYearlyChart })))

export function BudgetWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, language } = useFinanceCopy()
  const budgets = useLifeStore(state => state.budgets); const add = useLifeStore(state => state.addBudget); const update = useLifeStore(state => state.updateBudget); const remove = useLifeStore(state => state.deleteBudget); const settings = useLifeStore(state => state.settings)
  const [open, setOpen] = useState(false); const [category, setCategory] = useState(''); const [planned, setPlanned] = useState(0); const [icon, setIcon] = useState('○')
  const totalSpent = budgets.reduce((sum, item) => sum + item.spent, 0); const totalPlanned = budgets.reduce((sum, item) => sum + item.planned, 0); const overall = totalPlanned > 0 ? totalSpent / totalPlanned * 100 : 0
  const submit = () => { if (!category.trim() || planned <= 0) return; add({ category: category.trim(), planned, icon: icon.trim() || '○' }); setCategory(''); setPlanned(0); setIcon('○'); setOpen(false) }
  const content = <>
    <div className="module-toolbar"><span className="transaction-count">{budgets.length} {l('catégorie(s)', 'categories')}</span><Button size="sm" onClick={() => setOpen(true)}><Plus size={15} /> {l('Ajouter', 'Add')}</Button></div>
    {budgets.length ? <><div className="budget-summary"><span><small>{l('Budget utilisé', 'Budget used')}</small><strong>{currency(totalSpent, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)} <em>/ {currency(totalPlanned, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</em></strong></span><Badge tone={overall > 80 ? 'warning' : 'success'}>{Math.round(overall)}%</Badge></div><div className={`budget-list ${expanded ? 'expanded-list' : ''}`}>{budgets.map(item => { const pct = item.planned > 0 ? item.spent / item.planned * 100 : 0; return <article key={item.id}><div><span className="category-icon">{item.icon}</span><span><strong>{localizeFinanceCategory(item.category, language)}</strong><small>{currency(item.spent, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)} {l('sur', 'of')} {currency(item.planned, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</small></span>{expanded ? <><Input type="number" min="0" aria-label={`${l('Budget', 'Budget')} ${localizeFinanceCategory(item.category, language)}`} value={item.planned || ''} onChange={event => update(item.id, { planned: Number(event.target.value) })} /><IconButton label={l('Supprimer', 'Delete')} onClick={() => remove(item.id)}><Trash2 size={14} /></IconButton></> : <em>{Math.round(pct)}%</em>}</div><Progress value={pct} tone={pct > 100 ? 'danger' : pct >= 80 ? 'warning' : 'success'} /></article> })}</div>{expanded && <p className="insight-line">{l('Budget encore disponible :', 'Budget still available:')} <strong>{currency(Math.max(0, totalPlanned - totalSpent), settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong></p>}</> : <EmptyState icon={<CircleDollarSign size={22} />} title={l('Aucun budget pour le moment', 'No budget yet')} text={l('Créez vos propres catégories et montants mensuels.', 'Create your own categories and monthly amounts.')} action={<Button size="sm" onClick={() => setOpen(true)}><Plus size={14} /> {l('Créer un budget', 'Create a budget')}</Button>} />}
    <Modal open={open} onClose={() => setOpen(false)} title={l('Nouvelle catégorie de budget', 'New budget category')}><div className="form-grid"><Field label={l('Catégorie', 'Category')}><Input autoFocus value={category} onChange={event => setCategory(event.target.value)} /></Field><Field label={l('Montant prévu', 'Planned amount')}><Input type="number" min="0" value={planned || ''} onChange={event => setPlanned(Number(event.target.value))} /></Field><Field label={l('Icône', 'Icon')}><Input value={icon} maxLength={2} onChange={event => setIcon(event.target.value)} /></Field></div><div className="modal-actions"><Button variant="ghost" onClick={() => setOpen(false)}>{l('Annuler', 'Cancel')}</Button><Button onClick={submit}>{l('Ajouter', 'Add')}</Button></div></Modal>
  </>
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="budget" title={l('Budget mensuel', 'Monthly budget')} icon={CircleDollarSign} eyebrow={`${budgets.length} ${l('catégorie(s)', 'categories')}`}>{content}</Widget>
}

export function SavingsWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, language } = useFinanceCopy()
  const savings = useLifeStore(state => state.savings); const add = useLifeStore(state => state.addSavings); const contribute = useLifeStore(state => state.contributeSavings); const remove = useLifeStore(state => state.deleteSavings); const settings = useLifeStore(state => state.settings)
  const [selected, setSelected] = useState(savings[0]?.id ?? ''); const [amount, setAmount] = useState(0); const [open, setOpen] = useState<'contribute' | 'create' | null>(null); const [title, setTitle] = useState(''); const [target, setTarget] = useState(0); const [current, setCurrent] = useState(0); const [dueDate, setDueDate] = useState(''); const [icon, setIcon] = useState('◇')
  const primary = savings.find(item => item.id === selected) ?? savings[0]
  const createGoal = () => { if (!title.trim() || target <= 0 || !dueDate) return; add({ title: title.trim(), target, current: Math.min(current, target), dueDate, icon: icon.trim() || '◇' }); setTitle(''); setTarget(0); setCurrent(0); setDueDate(''); setIcon('◇'); setOpen(null) }
  const content = !primary ? <><EmptyState icon={<WalletCards size={22} />} title={l('Aucun objectif d’épargne', 'No savings goal')} text={l('Ajoutez un projet avec votre montant et votre échéance.', 'Add a project with your own amount and due date.')} action={<Button size="sm" onClick={() => setOpen('create')}><Plus size={14} /> {l('Créer un objectif', 'Create a goal')}</Button>} /><SavingsCreateModal open={open === 'create'} onClose={() => setOpen(null)} onSubmit={createGoal} l={l} title={title} setTitle={setTitle} target={target} setTarget={setTarget} current={current} setCurrent={setCurrent} dueDate={dueDate} setDueDate={setDueDate} icon={icon} setIcon={setIcon} /></> : (() => {
    const pct = primary.target > 0 ? primary.current / primary.target * 100 : 0; const days = Math.max(0, Math.ceil((new Date(primary.dueDate).getTime() - Date.now()) / 86400000)); const months = Math.max(1, Math.ceil(days / 30)); const monthly = Math.max(0, Math.ceil((primary.target - primary.current) / months))
    return <><div className="module-toolbar"><div className="savings-tabs">{savings.map(item => <button className={primary.id === item.id ? 'active' : ''} key={item.id} onClick={() => setSelected(item.id)}>{item.icon}</button>)}</div><Button size="sm" variant="secondary" onClick={() => setOpen('create')}><Plus size={14} /> {l('Objectif', 'Goal')}</Button></div><div className="savings-main"><RingProgress value={pct} size={expanded ? 150 : 116}><strong>{Math.round(pct)}%</strong></RingProgress><div><Badge tone="success">{l('En progression', 'In progress')}</Badge><h4>{localizeSavingsTitle(primary.title, language)}</h4><strong>{currency(primary.current, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong><p>{l('sur', 'of')} {currency(primary.target, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</p><Button size="sm" variant="secondary" onClick={() => { setAmount(0); setOpen('contribute') }}><Plus size={14} /> {l('Contribuer', 'Contribute')}</Button></div></div><div className="savings-meta"><span><small>{l('Reste', 'Remaining')}</small><strong>{currency(Math.max(0, primary.target - primary.current), settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong></span><span><small>{l('Par mois', 'Per month')}</small><strong>{currency(monthly, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong></span><span><small>{l('Échéance', 'Due')}</small><strong>{days} {l('jours', 'days')}</strong></span></div>{expanded && <Button size="sm" variant="ghost" onClick={() => remove(primary.id)}><Trash2 size={14} /> {l('Supprimer cet objectif', 'Delete this goal')}</Button>}<Modal open={open === 'contribute'} onClose={() => setOpen(null)} title={`${l('Contribuer à', 'Contribute to')} “${localizeSavingsTitle(primary.title, language)}”`}><div className="form-stack"><Field label={l('Montant', 'Amount')}><Input type="number" min={1} value={amount || ''} onChange={event => setAmount(Number(event.target.value))} /></Field><div className="quick-amounts">{[100, 250, 500, 1000].map(value => <button key={value} onClick={() => setAmount(value)}>+{value}</button>)}</div><div className="modal-actions"><Button variant="ghost" onClick={() => setOpen(null)}>{l('Annuler', 'Cancel')}</Button><Button disabled={amount <= 0} onClick={() => { contribute(primary.id, amount); setOpen(null) }}>{l('Ajouter à l’épargne', 'Add to savings')}</Button></div></div></Modal><SavingsCreateModal open={open === 'create'} onClose={() => setOpen(null)} onSubmit={createGoal} l={l} title={title} setTitle={setTitle} target={target} setTarget={setTarget} current={current} setCurrent={setCurrent} dueDate={dueDate} setDueDate={setDueDate} icon={icon} setIcon={setIcon} /></>
  })()
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="savings" title={l('Objectif d’épargne', 'Savings goal')} icon={WalletCards}>{content}</Widget>
}

function SavingsCreateModal({ open, onClose, onSubmit, l, title, setTitle, target, setTarget, current, setCurrent, dueDate, setDueDate, icon, setIcon }: {
  open: boolean; onClose: () => void; onSubmit: () => void; l: (fr: string, en: string) => string; title: string; setTitle: (value: string) => void; target: number; setTarget: (value: number) => void; current: number; setCurrent: (value: number) => void; dueDate: string; setDueDate: (value: string) => void; icon: string; setIcon: (value: string) => void
}) {
  return <Modal open={open} onClose={onClose} title={l('Nouvel objectif d’épargne', 'New savings goal')}><div className="form-grid"><Field label={l('Nom du projet', 'Project name')}><Input autoFocus value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label={l('Montant cible', 'Target amount')}><Input type="number" min="1" value={target || ''} onChange={event => setTarget(Number(event.target.value))} /></Field><Field label={l('Déjà épargné', 'Already saved')}><Input type="number" min="0" value={current || ''} onChange={event => setCurrent(Number(event.target.value))} /></Field><Field label={l('Échéance', 'Due date')}><Input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></Field><Field label={l('Icône', 'Icon')}><Input value={icon} maxLength={2} onChange={event => setIcon(event.target.value)} /></Field></div><div className="modal-actions"><Button variant="ghost" onClick={onClose}>{l('Annuler', 'Cancel')}</Button><Button onClick={onSubmit}>{l('Créer', 'Create')}</Button></div></Modal>
}

export function TransactionsWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, language } = useFinanceCopy()
  const transactions = useLifeStore(state => state.transactions); const add = useLifeStore(state => state.addTransaction); const update = useLifeStore(state => state.updateTransaction); const remove = useLifeStore(state => state.deleteTransaction); const budgets = useLifeStore(state => state.budgets); const settings = useLifeStore(state => state.settings)
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<string | null>(null); const [search, setSearch] = useState(''); const [title, setTitle] = useState(''); const [amount, setAmount] = useState(0); const [type, setType] = useState<TransactionType>('expense'); const [category, setCategory] = useState(''); const [date, setDate] = useState(todayISO())
  const list = transactions.filter(item => item.title.toLowerCase().includes(search.toLowerCase()) || item.category.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date))
  const resetForm = () => { setOpen(false); setEditing(null); setTitle(''); setAmount(0); setType('expense'); setCategory(''); setDate(todayISO()) }
  const create = () => { setEditing(null); setTitle(''); setAmount(0); setType('expense'); setCategory(''); setDate(todayISO()); setOpen(true) }
  const edit = (item: Transaction) => { setEditing(item.id); setTitle(item.title); setAmount(item.amount); setType(item.type); setCategory(item.category); setDate(item.date); setOpen(true) }
  const submit = () => { if (!title.trim() || !category.trim() || amount <= 0) return; const values = { title: title.trim(), amount, type, category: category.trim(), date }; if (editing) update(editing, values); else add(values); resetForm() }
  const exportCSV = () => downloadFile('lifeos-transactions.csv', `\uFEFF${toCSV(transactions as unknown as Record<string, unknown>[])}`, 'text/csv;charset=utf-8')
  const content = <>
    <div className="module-toolbar">{expanded ? <label className="table-search"><Search size={15} /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder={l('Rechercher…', 'Search…')} /></label> : <span className="transaction-count">{list.length} {l('mouvements', 'entries')}</span>}<div className="toolbar-actions"><IconButton label={l('Exporter CSV', 'Export CSV')} onClick={exportCSV}><Download size={16} /></IconButton><Button size="sm" onClick={create}><Plus size={15} /> {l('Ajouter', 'Add')}</Button></div></div>
    {list.length ? <div className={`transaction-list ${expanded ? 'expanded-list' : ''}`}>{list.slice(0, expanded ? 50 : 6).map(item => <article key={item.id}><span className="transaction-avatar">{item.category.slice(0, 1)}</span><div><strong>{item.title}</strong><small>{localizeFinanceCategory(item.category, language)} · {shortDate(item.date, language, settings.dateFormat)}</small></div><em className={item.type}>{item.type === 'income' ? '+' : '−'}{currency(item.amount, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</em>{expanded && <><IconButton label={l('Modifier', 'Edit')} onClick={() => edit(item)}><Edit3 size={14} /></IconButton><IconButton label={l('Supprimer', 'Delete')} onClick={() => remove(item.id)}><Trash2 size={14} /></IconButton></>}</article>)}</div> : <EmptyState icon={<ReceiptText size={22} />} title={search ? l('Aucun résultat', 'No results') : l('Aucune transaction', 'No transactions')} text={search ? l('Essayez une autre recherche.', 'Try another search.') : l('Ajoutez votre premier revenu ou votre première dépense.', 'Add your first income or expense.')} action={!search ? <Button size="sm" onClick={create}><Plus size={14} /> {l('Ajouter', 'Add')}</Button> : undefined} />}
    <Modal open={open} onClose={resetForm} title={editing ? l('Modifier la transaction', 'Edit transaction') : l('Nouvelle transaction', 'New transaction')}><div className="form-grid"><Field label={l('Libellé', 'Label')}><Input autoFocus value={title} onChange={event => setTitle(event.target.value)} placeholder={l('Ex. Courses', 'E.g. Groceries')} /></Field><Field label={l('Montant', 'Amount')}><Input type="number" min="0" value={amount || ''} onChange={event => setAmount(Number(event.target.value))} /></Field><Field label={l('Type', 'Type')}><Select value={type} onChange={event => setType(event.target.value as TransactionType)}><option value="expense">{l('Dépense', 'Expense')}</option><option value="income">{l('Revenu', 'Income')}</option></Select></Field><Field label={l('Catégorie', 'Category')}><Input list="lifeos-budget-categories" value={category} onChange={event => setCategory(event.target.value)} /><datalist id="lifeos-budget-categories">{budgets.map(item => <option key={item.id} value={item.category} />)}</datalist></Field><Field label={l('Date', 'Date')}><Input type="date" value={date} onChange={event => setDate(event.target.value)} /></Field></div><div className="modal-actions"><Button variant="ghost" onClick={resetForm}>{l('Annuler', 'Cancel')}</Button><Button onClick={submit}>{editing ? l('Mettre à jour', 'Update') : l('Enregistrer', 'Save')}</Button></div></Modal>
  </>
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="transactions" title="Transactions" icon={ReceiptText} eyebrow={l('Derniers mouvements', 'Latest entries')}>{content}</Widget>
}

export function LoanCalculator({ widget = true }: { widget?: boolean }) {
  const { l } = useFinanceCopy()
  const settings = useLifeStore(state => state.settings); const [principal, setPrincipal] = useState(0); const [rate, setRate] = useState(0); const [years, setYears] = useState(15); const result = useMemo(() => calculateLoan(principal, rate, years), [principal, rate, years])
  const content = <><div className="loan-inputs"><Field label={l('Montant', 'Amount')}><Input type="number" min="0" value={principal || ''} onChange={event => setPrincipal(Number(event.target.value))} /></Field><Field label={l('Taux annuel', 'Annual rate')}><div className="input-suffix"><Input type="number" min="0" step=".1" value={rate || ''} onChange={event => setRate(Number(event.target.value))} /><span>%</span></div></Field><Field label={l('Durée', 'Term')}><Select value={years} onChange={event => setYears(Number(event.target.value))}>{[5, 10, 15, 20, 25, 30].map(value => <option value={value} key={value}>{value} {l('ans', 'years')}</option>)}</Select></Field></div><div className="loan-results"><article><small>{l('Mensualité', 'Monthly payment')}</small><strong>{currency(result.payment, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong></article><article><small>{l('Intérêts', 'Interest')}</small><strong>{currency(result.interest, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong></article><article><small>{l('Coût total', 'Total cost')}</small><strong>{currency(result.total, settings.currency, settings.language, settings.hideAmounts, settings.decimalSeparator)}</strong></article></div>{!widget && <Suspense fallback={<div className="chart-tall chart-placeholder" aria-hidden="true" />}><LoanYearlyChart data={result.yearly} currencyCode={settings.currency} language={settings.language} hideAmounts={settings.hideAmounts} decimalSeparator={settings.decimalSeparator} /></Suspense>}</>
  if (!widget) return <div className="standalone-module">{content}</div>
  return <Widget id="loan" title={l('Calculateur de prêt', 'Loan calculator')} icon={Landmark} eyebrow={l('Simulation instantanée', 'Instant simulation')}>{content}</Widget>
}
