import { useEffect, useMemo, useRef, useState } from 'react'
import {
  CalendarDays, Check, CheckSquare, ChevronLeft, ChevronRight, Circle, Edit3, Flame, Goal as GoalIcon,
  ListFilter, NotebookPen, Plus, Sparkles, StickyNote, Trash2, X,
} from 'lucide-react'
import { addDays, addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, getDay, isSameDay, isSameMonth, parseISO, startOfMonth, startOfWeek, subMonths } from 'date-fns'
import { enUS, fr } from 'date-fns/locale'
import { useLifeStore } from '../../store/useLifeStore'
import { dateLabel, relativeDate, timeLabel, todayISO } from '../../utils/formatters'
import type { Priority, TaskStatus } from '../../types'
import { Badge, Button, EmptyState, Field, IconButton, Input, Modal, Progress, Select, Textarea } from '../ui/primitives'
import { Widget } from '../dashboard/Widget'

function useModuleCopy() {
  const language = useLifeStore(state => state.settings.language)
  return { language, locale: language === 'en' ? enUS : fr, l: (french: string, english: string) => language === 'en' ? english : french }
}

function readNotePosition(id: string) {
  try { const value = Number(localStorage.getItem(`lifeos:note-position:${id}`) ?? 0); return Number.isFinite(value) && value >= 0 ? value : 0 } catch { return 0 }
}
function writeNotePosition(id: string, position: number) {
  try { localStorage.setItem(`lifeos:note-position:${id}`, String(position)) } catch { /* Note content is still persisted by Zustand. */ }
}

const priorityTone: Record<Priority, 'neutral' | 'warning' | 'danger' | 'info'> = { low: 'neutral', medium: 'warning', high: 'danger', urgent: 'danger' }
const nextStatus: Record<TaskStatus, TaskStatus> = { todo: 'doing', doing: 'done', done: 'todo' }
export function TasksWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, language } = useModuleCopy()
  const tasks = useLifeStore(state => state.tasks); const dateFormat = useLifeStore(state => state.settings.dateFormat); const setStatus = useLifeStore(state => state.setTaskStatus); const add = useLifeStore(state => state.addTask); const remove = useLifeStore(state => state.deleteTask); const update = useLifeStore(state => state.updateTask)
  const [filter, setFilter] = useState<'active' | 'all' | 'done'>('active'); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<string | null>(null); const [title, setTitle] = useState(''); const [priority, setPriority] = useState<Priority>('medium')
  const list = tasks.filter(task => filter === 'all' || (filter === 'done' ? task.status === 'done' : task.status !== 'done'))
  const submit = () => { if (!title.trim()) return; add({ title: title.trim(), priority, status: 'todo', dueDate: todayISO(1), category: language === 'en' ? 'Personal' : 'Personnel', tags: [], subtasks: [] }); setTitle(''); setOpen(false) }
  const content = <><div className="module-toolbar"><div className="segmented"><button className={filter === 'active' ? 'active' : ''} onClick={() => setFilter('active')}>{l('Actives', 'Active')}</button><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>{l('Toutes', 'All')}</button><button className={filter === 'done' ? 'active' : ''} onClick={() => setFilter('done')}>{l('Finies', 'Done')}</button></div><Button size="sm" onClick={() => setOpen(true)}><Plus size={15} /> {l('Ajouter', 'Add')}</Button></div>
    {list.length ? <div className={`task-list ${expanded ? 'expanded-list' : ''}`}>{list.slice(0, expanded ? 50 : 5).map(task => <div className={`task-row status-${task.status}`} key={task.id} draggable={expanded}>
      <button className="task-check" aria-label={`${l('Changer le statut de', 'Change status of')} ${task.title}`} onClick={() => setStatus(task.id, nextStatus[task.status])}>{task.status === 'done' ? <Check size={15} /> : task.status === 'doing' ? <Circle size={14} fill="currentColor" /> : <Circle size={15} />}</button>
      <div className="task-copy">{editing === task.id ? <Input autoFocus value={task.title} onChange={event => update(task.id, { title: event.target.value })} onBlur={() => setEditing(null)} onKeyDown={event => event.key === 'Enter' && setEditing(null)} /> : <button className="task-title" onDoubleClick={() => setEditing(task.id)} onClick={() => setStatus(task.id, nextStatus[task.status])}>{task.title}</button>}<div><Badge tone={priorityTone[task.priority]}>{task.priority}</Badge><small>{dateLabel(task.dueDate, 'd MMM', language, dateFormat)}</small>{task.subtasks.length > 0 && <small>{task.subtasks.filter(s => s.done).length}/{task.subtasks.length}</small>}</div></div>
      <IconButton label={l('Modifier', 'Edit')} onClick={() => setEditing(task.id)}><Edit3 size={14} /></IconButton><IconButton label={l('Supprimer', 'Delete')} onClick={() => remove(task.id)}><Trash2 size={14} /></IconButton>
    </div>)}</div> : <EmptyState icon={<CheckSquare size={22} />} title={tasks.length ? l('Aucune tâche dans ce filtre', 'No tasks in this filter') : l('Aucune tâche', 'No tasks')} text={tasks.length ? l('Choisissez un autre filtre.', 'Choose another filter.') : l('Ajoutez votre première prochaine action.', 'Add your first next action.')} action={!tasks.length ? <Button size="sm" onClick={() => setOpen(true)}><Plus size={14} /> {l('Créer une tâche', 'Create a task')}</Button> : undefined} />}
    {!expanded && tasks.filter(task => task.status !== 'done').length > 5 && <p className="module-footnote">+{tasks.filter(task => task.status !== 'done').length - 5} {l('autres tâches', 'more tasks')}</p>}
    <Modal open={open} onClose={() => setOpen(false)} title={l('Nouvelle tâche', 'New task')} description={l('Ajoutez une prochaine action claire.', 'Add a clear next action.')}><div className="form-stack"><Field label={l('Titre', 'Title')}><Input autoFocus value={title} onChange={event => setTitle(event.target.value)} onKeyDown={event => event.key === 'Enter' && submit()} placeholder={l('Ex. Préparer le rendez-vous', 'E.g. Prepare the meeting')} /></Field><Field label={l('Priorité', 'Priority')}><Select value={priority} onChange={event => setPriority(event.target.value as Priority)}><option value="low">{l('Basse', 'Low')}</option><option value="medium">{l('Moyenne', 'Medium')}</option><option value="high">{l('Haute', 'High')}</option><option value="urgent">{l('Urgente', 'Urgent')}</option></Select></Field><div className="modal-actions"><Button variant="ghost" onClick={() => setOpen(false)}>{l('Annuler', 'Cancel')}</Button><Button onClick={submit}>{l('Créer la tâche', 'Create task')}</Button></div></div></Modal></>
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="tasks" title={l('Tâches', 'Tasks')} icon={CheckSquare} eyebrow={`${tasks.filter(task => task.status === 'done').length}/${tasks.length} ${l('terminées', 'completed')}`}>{content}</Widget>
}

export function NotesWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, language } = useModuleCopy()
  const notes = useLifeStore(state => state.notes); const add = useLifeStore(state => state.addNote); const update = useLifeStore(state => state.updateNote); const remove = useLifeStore(state => state.deleteNote)
  const [activeId, setActiveId] = useState<string | null>(null); const [draftTitle, setDraftTitle] = useState(''); const [draftContent, setDraftContent] = useState(''); const readerRef = useRef<HTMLTextAreaElement>(null); const readingPosition = useRef(0)
  const active = notes.find(note => note.id === activeId)
  useEffect(() => {
    if (!active) return
    setDraftTitle(active.title); setDraftContent(active.content)
    readingPosition.current = readNotePosition(active.id)
    const frame = window.requestAnimationFrame(() => { if (readerRef.current) readerRef.current.scrollTop = readingPosition.current })
    return () => window.cancelAnimationFrame(frame)
  }, [activeId])
  useEffect(() => {
    if (!activeId || !active) return
    const timer = window.setTimeout(() => {
      if (draftTitle !== active.title || draftContent !== active.content) update(activeId, { title: draftTitle, content: draftContent })
    }, 500)
    return () => window.clearTimeout(timer)
  }, [activeId, draftTitle, draftContent, active?.title, active?.content, update])
  const persistReader = () => {
    if (!activeId) return
    update(activeId, { title: draftTitle.trim() || l('Sans titre', 'Untitled'), content: draftContent })
    writeNotePosition(activeId, readingPosition.current)
  }
  const closeReader = () => { persistReader(); setActiveId(null) }
  const openNew = () => { const id = add(); setActiveId(id) }
  const visibleNotes = expanded ? notes : notes.slice(0, 3)
  const editorSize = draftContent.length > 4500 ? 'long' : draftContent.length > 900 ? 'medium' : 'short'
  const content = <>{notes.length ? <div className={`notes-grid ${expanded ? 'notes-library' : ''}`}>{visibleNotes.map(note => <article className="note-card" key={note.id} onClick={() => setActiveId(note.id)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setActiveId(note.id) } }} role="button" tabIndex={0} aria-label={`${l('Ouvrir la note', 'Open note')} ${note.title}`}><div className="note-top"><span className="note-card-icon"><StickyNote size={14} /></span><strong>{note.title || l('Sans titre', 'Untitled')}</strong><IconButton label={l('Supprimer la note', 'Delete note')} onClick={event => { event.stopPropagation(); if (activeId === note.id) setActiveId(null); remove(note.id) }}><X size={14} /></IconButton></div><p>{note.content || l('Note vide — cliquez pour commencer à écrire.', 'Empty note — click to start writing.')}</p><footer><small>{relativeDate(note.updatedAt, language)}</small><span>{note.content.trim() ? note.content.trim().split(/\s+/).length : 0} {l('mots', 'words')}</span></footer></article>)}</div> : <EmptyState icon={<StickyNote size={22} />} title={l('Aucune note', 'No notes')} text={l('Créez une note vide et écrivez uniquement ce qui vous appartient.', 'Create a blank note and write only what is yours.')} action={<Button size="sm" onClick={openNew}><Plus size={14} /> {l('Nouvelle note', 'New note')}</Button>} />}{expanded && <div className="notes-library-footer"><span>{notes.length} {l('notes · toutes sont affichées', 'notes · all are displayed')}</span><Button variant="secondary" onClick={openNew}><Plus size={15} /> {l('Nouvelle note', 'New note')}</Button></div>}<Modal open={Boolean(active)} onClose={closeReader} size="lg" title={l('Lecteur de note', 'Note reader')} description={l('Lecture confortable · sauvegarde automatique · reprise à votre position', 'Comfortable reading · autosave · resume at your position')}><div className={`note-reader note-reader-${editorSize}`}><div className="note-reader-heading"><Input value={draftTitle} onChange={event => setDraftTitle(event.target.value)} aria-label={l('Titre de la note', 'Note title')} placeholder={l('Titre de la note', 'Note title')} /><Badge tone="success"><Check size={11} /> {l('Auto', 'Auto')}</Badge></div><Textarea ref={readerRef} value={draftContent} onChange={event => setDraftContent(event.target.value)} onScroll={event => { readingPosition.current = event.currentTarget.scrollTop }} aria-label={l('Contenu de la note', 'Note content')} placeholder={l('Écrivez librement…', 'Write freely…')} /><footer><span>{draftContent.trim() ? draftContent.trim().split(/\s+/).length : 0} {l('mots', 'words')} · {draftContent.length} {l('caractères', 'characters')}</span><span><Check size={13} /> {l('Sauvegarde automatique', 'Autosaved')}</span><Button onClick={closeReader}>{l('Fermer et reprendre plus tard', 'Close and resume later')}</Button></footer></div></Modal></>
  if (expanded) return <div className="standalone-module notes-standalone">{content}</div>
  return <Widget id="notes" title={l('Notes rapides', 'Quick notes')} icon={StickyNote} action={<IconButton label={l('Ajouter une note', 'Add note')} onClick={openNew}><Plus size={16} /></IconButton>}>{content}</Widget>
}

function weekDates() { const start = startOfWeek(new Date(), { weekStartsOn: 1 }); return Array.from({ length: 7 }, (_, i) => addDays(start, i)) }
export function HabitsWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, locale, language } = useModuleCopy()
  const habits = useLifeStore(state => state.habits); const dateFormat = useLifeStore(state => state.settings.dateFormat); const add = useLifeStore(state => state.addHabit); const toggle = useLifeStore(state => state.toggleHabit); const remove = useLifeStore(state => state.deleteHabit); const days = useMemo(weekDates, [])
  const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [icon, setIcon] = useState('○')
  const submit = () => { if (!name.trim()) return; add(name.trim(), icon.trim() || '○'); setName(''); setIcon('○'); setOpen(false) }
  const completed = habits.reduce((total, habit) => total + days.filter(day => habit.done[format(day, 'yyyy-MM-dd')]).length, 0); const consistency = habits.length ? Math.round(completed / (habits.length * days.length) * 100) : 0
  const table = <div className={`habit-table ${expanded ? 'expanded' : ''}`}><div className="habit-head"><span>{l('Habitude', 'Habit')}</span>{days.map(day => <small key={day.toISOString()}>{format(day, 'EEEEE', { locale })}</small>)}<small>{l('Série', 'Streak')}</small></div>{habits.map(habit => <div className="habit-row" key={habit.id}><strong><span>{habit.icon}</span>{habit.name}{expanded && <IconButton label={l('Supprimer', 'Delete')} onClick={() => remove(habit.id)}><Trash2 size={13} /></IconButton>}</strong>{days.map(day => { const key = format(day, 'yyyy-MM-dd'); const done = habit.done[key]; const missed = habit.missed[key]; return <button key={key} aria-label={`${habit.name} ${dateLabel(key, 'd MMM', language, dateFormat)}`} className={done ? 'habit-done' : missed ? 'habit-missed' : ''} onClick={() => toggle(habit.id, key)}>{done ? <Check size={14} /> : missed ? <X size={14} /> : <Circle size={14} />}</button> })}<span className="streak"><Flame size={14} /> {Object.keys(habit.done).filter(key => habit.done[key]).length}</span></div>)}</div>
  const content = <><div className="module-toolbar"><span className="transaction-count">{habits.length} {l('habitude(s)', 'habits')}</span><Button size="sm" onClick={() => setOpen(true)}><Plus size={14} /> {l('Ajouter', 'Add')}</Button></div>{habits.length ? table : <EmptyState icon={<Sparkles size={22} />} title={l('Aucune habitude', 'No habits')} text={l('Créez la première habitude que vous voulez vraiment suivre.', 'Create the first habit you genuinely want to track.')} action={<Button size="sm" onClick={() => setOpen(true)}><Plus size={14} /> {l('Créer une habitude', 'Create a habit')}</Button>} />}{expanded && habits.length > 0 && <div className="habit-insight"><Sparkles size={18} /><span><strong>{consistency}% {l('de régularité cette semaine', 'consistency this week')}</strong><small>{l('Calculé uniquement depuis vos propres validations.', 'Calculated only from your own check-ins.')}</small></span></div>}<Modal open={open} onClose={() => setOpen(false)} title={l('Nouvelle habitude', 'New habit')}><div className="form-grid"><Field label={l('Nom', 'Name')}><Input autoFocus value={name} onChange={event => setName(event.target.value)} /></Field><Field label={l('Icône', 'Icon')}><Input maxLength={2} value={icon} onChange={event => setIcon(event.target.value)} /></Field></div><div className="modal-actions"><Button variant="ghost" onClick={() => setOpen(false)}>{l('Annuler', 'Cancel')}</Button><Button onClick={submit}>{l('Ajouter', 'Add')}</Button></div></Modal></>
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="habits" title={l('Habitudes', 'Habits')} icon={Sparkles} eyebrow={l('Cette semaine', 'This week')}>{content}</Widget>
}

export function JournalWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, locale, language } = useModuleCopy()
  const entries = useLifeStore(state => state.journal); const save = useLifeStore(state => state.saveJournal); const settings = useLifeStore(state => state.settings)
  const today = todayISO(); const current = entries.find(entry => entry.date === today); const [mood, setMood] = useState(current?.mood ?? ''); const [content, setContent] = useState(current?.content ?? ''); const [unlocked, setUnlocked] = useState(!settings.journalLocked); const [pin, setPin] = useState('')
  useEffect(() => { const id = window.setTimeout(() => { if (content || current) save(today, mood, content) }, 400); return () => window.clearTimeout(id) }, [content, mood])
  if (!unlocked) return <Widget id="journal" title="Journal" icon={NotebookPen}><div className="journal-lock"><span>{l('Journal protégé', 'Protected journal')}</span><Input type="password" inputMode="numeric" maxLength={4} value={pin} onChange={event => setPin(event.target.value)} placeholder={l('PIN à 4 chiffres', '4-digit PIN')} /><Button size="sm" onClick={() => pin === settings.pin && setUnlocked(true)}>{l('Déverrouiller', 'Unlock')}</Button></div></Widget>
  const contentNode = <><div className="mood-picker">{['😄', '😊', '😐', '😟', '😢'].map(item => <button className={mood === item ? 'active' : ''} key={item} onClick={() => setMood(item)}>{item}</button>)}</div><Textarea className="journal-editor" value={content} onChange={event => setContent(event.target.value)} placeholder={l('Comment s’est passée votre journée ?', 'How was your day?')} /><div className="autosave"><Check size={12} /> {l('Sauvegarde automatique', 'Autosaved')}</div>{expanded && <div className="journal-history">{entries.filter(entry => entry.date !== today).map(entry => <article key={entry.id}><span>{entry.mood}</span><div><strong>{dateLabel(entry.date, 'EEEE d MMMM', language, settings.dateFormat)}</strong><p>{entry.content}</p></div></article>)}</div>}</>
  if (expanded) return <div className="standalone-module">{contentNode}</div>
  return <Widget id="journal" title="Journal" icon={NotebookPen} eyebrow={format(new Date(), 'd MMMM', { locale })}>{contentNode}</Widget>
}

export function GoalsWidget({ expanded = false }: { expanded?: boolean }) {
  const { l } = useModuleCopy()
  const goals = useLifeStore(state => state.goals); const add = useLifeStore(state => state.addGoal); const update = useLifeStore(state => state.updateGoal); const remove = useLifeStore(state => state.deleteGoal)
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [category, setCategory] = useState(''); const [target, setTarget] = useState(0); const [unit, setUnit] = useState(''); const [dueDate, setDueDate] = useState(todayISO(30))
  const submit = () => { if (!title.trim() || !category.trim() || !unit.trim() || target <= 0 || !dueDate) return; add({ title: title.trim(), category: category.trim(), progress: 0, target, unit: unit.trim(), dueDate }); setTitle(''); setCategory(''); setTarget(0); setUnit(''); setDueDate(todayISO(30)); setOpen(false) }
  const list = <div className="goal-list">{goals.map(goal => { const pct = goal.target ? goal.progress / goal.target * 100 : 0; return <article className="goal-row" key={goal.id}><div className="goal-heading"><span><Badge>{goal.category}</Badge><strong>{goal.title}</strong></span><span className="goal-actions"><button onClick={() => update(goal.id, { progress: Math.min(goal.target, goal.progress + 1) })}>+1</button>{expanded && <IconButton label={l('Supprimer', 'Delete')} onClick={() => remove(goal.id)}><Trash2 size={14} /></IconButton>}</span></div><Progress value={pct} /><div className="goal-meta"><span>{goal.progress} / {goal.target} {goal.unit}</span><span>{Math.round(pct)}%</span></div>{expanded && goal.milestones.length > 0 && <div className="milestones">{goal.milestones.map(milestone => <label key={milestone.id}><input type="checkbox" checked={milestone.done} readOnly /> {milestone.title}</label>)}</div>}</article> })}</div>
  const content = <><div className="module-toolbar"><span className="transaction-count">{goals.length} {l('objectif(s)', 'goals')}</span><Button size="sm" onClick={() => setOpen(true)}><Plus size={14} /> {l('Ajouter', 'Add')}</Button></div>{goals.length ? list : <EmptyState icon={<GoalIcon size={22} />} title={l('Aucun objectif', 'No goals')} text={l('Définissez un objectif avec votre propre mesure et votre échéance.', 'Define a goal with your own measure and due date.')} action={<Button size="sm" onClick={() => setOpen(true)}><Plus size={14} /> {l('Créer un objectif', 'Create a goal')}</Button>} />}<Modal open={open} onClose={() => setOpen(false)} title={l('Nouvel objectif', 'New goal')}><div className="form-grid"><Field label={l('Titre', 'Title')}><Input autoFocus value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label={l('Catégorie', 'Category')}><Input value={category} onChange={event => setCategory(event.target.value)} /></Field><Field label={l('Cible', 'Target')}><Input type="number" min="1" value={target || ''} onChange={event => setTarget(Number(event.target.value))} /></Field><Field label={l('Unité', 'Unit')}><Input value={unit} onChange={event => setUnit(event.target.value)} /></Field><Field label={l('Échéance', 'Due date')}><Input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></Field></div><div className="modal-actions"><Button variant="ghost" onClick={() => setOpen(false)}>{l('Annuler', 'Cancel')}</Button><Button onClick={submit}>{l('Créer', 'Create')}</Button></div></Modal></>
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="goals" title={l('Objectifs SMART', 'SMART goals')} icon={GoalIcon} eyebrow={l('En progression', 'In progress')}>{content}</Widget>
}

export function CalendarWidget({ expanded = false }: { expanded?: boolean }) {
  const { l, locale, language } = useModuleCopy()
  const events = useLifeStore(state => state.events); const settings = useLifeStore(state => state.settings); const addEvent = useLifeStore(state => state.addEvent); const removeEvent = useLifeStore(state => state.deleteEvent); const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState(new Date()); const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [time, setTime] = useState('09:00')
  const days = useMemo(() => eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: settings.firstDay }), end: endOfWeek(endOfMonth(month), { weekStartsOn: settings.firstDay }) }), [month, settings.firstDay])
  const weekLabels = settings.firstDay === 0 ? (language === 'en' ? ['S', 'M', 'T', 'W', 'T', 'F', 'S'] : ['D', 'L', 'M', 'M', 'J', 'V', 'S']) : (language === 'en' ? ['M', 'T', 'W', 'T', 'F', 'S', 'S'] : ['L', 'M', 'M', 'J', 'V', 'S', 'D'])
  const selectedEvents = events.filter(event => isSameDay(parseISO(event.date), selected))
  const submit = () => { if (!title.trim()) return; addEvent({ title: title.trim(), date: format(selected, 'yyyy-MM-dd'), time, color: '#66736a' }); setTitle(''); setOpen(false) }
  const content = <><div className="calendar-toolbar"><IconButton label={l('Mois précédent', 'Previous month')} onClick={() => setMonth(value => subMonths(value, 1))}><ChevronLeft size={17} /></IconButton><strong>{format(month, 'MMMM yyyy', { locale })}</strong><IconButton label={l('Mois suivant', 'Next month')} onClick={() => setMonth(value => addMonths(value, 1))}><ChevronRight size={17} /></IconButton></div><div className={`calendar-grid ${expanded ? 'calendar-expanded' : ''}`}>{weekLabels.map((day, index) => <small key={index}>{day}</small>)}{days.map(day => { const date = format(day, 'yyyy-MM-dd'); const dayEvents = events.filter(event => event.date === date); return <button key={date} className={`${!isSameMonth(day, month) ? 'outside' : ''} ${isSameDay(day, new Date()) ? 'today' : ''} ${isSameDay(day, selected) ? 'selected' : ''}`} onClick={() => setSelected(day)}><span>{format(day, 'd')}</span>{dayEvents.length > 0 && <i style={{ background: dayEvents[0].color }} />}</button> })}</div><div className="calendar-events"><div><strong>{isSameDay(selected, new Date()) ? l('Aujourd’hui', 'Today') : dateLabel(format(selected, 'yyyy-MM-dd'), 'd MMMM', language, settings.dateFormat)}</strong><IconButton label={l('Ajouter un événement', 'Add event')} onClick={() => setOpen(true)}><Plus size={15} /></IconButton></div>{selectedEvents.length ? selectedEvents.map(event => <article key={event.id}><i style={{ background: event.color }} /><span><strong>{event.title}</strong><small>{timeLabel(event.time, language, settings.hour12)}</small></span>{expanded && <IconButton label={l('Supprimer', 'Delete')} onClick={() => removeEvent(event.id)}><Trash2 size={14} /></IconButton>}</article>) : <small>{l('Aucun événement', 'No events')}</small>}</div><Modal open={open} onClose={() => setOpen(false)} title={l('Nouvel événement', 'New event')}><div className="form-stack"><Field label={l('Titre', 'Title')}><Input autoFocus value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label={l('Date', 'Date')}><Input type="date" value={format(selected, 'yyyy-MM-dd')} onChange={event => setSelected(parseISO(event.target.value))} /></Field><Field label={l('Heure', 'Time')}><Input type="time" value={time} onChange={event => setTime(event.target.value)} /></Field><div className="modal-actions"><Button variant="ghost" onClick={() => setOpen(false)}>{l('Annuler', 'Cancel')}</Button><Button onClick={submit}>{l('Ajouter', 'Add')}</Button></div></div></Modal></>
  if (expanded) return <div className="standalone-module">{content}</div>
  return <Widget id="calendar" title={l('Calendrier', 'Calendar')} icon={CalendarDays}>{content}</Widget>
}
