import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import {
  Bot, CalendarSync, Check, Cloud, Code2, Download, FileBarChart, KeyRound, Landmark, LifeBuoy, Palette, PlugZap, RefreshCw, Sparkles, Users, WifiOff,
} from 'lucide-react'
import { useLifeStore } from '../../store/useLifeStore'
import { translate } from '../../i18n/translations'
import { currency, downloadFile, toCSV } from '../../utils/formatters'
import { fadeInUp, pageTransition, staggerContainer } from '../../utils/animations'
import { Badge, Button, Field, Input, Select, Toggle } from '../ui/primitives'

const features = [
  { id: 'ai', title: 'IA avancée', text: 'Analyses contextuelles et recommandations adaptées à vos données.', icon: Bot, group: 'Intelligence' },
  { id: 'reports', title: 'Rapports automatiques', text: 'Bilans financiers exportables, quand vous le souhaitez.', icon: FileBarChart, group: 'Données' },
  { id: 'bank', title: 'Synchronisation bancaire', text: 'Connecteur local de démonstration et import de transactions.', icon: Landmark, group: 'Finances' },
  { id: 'cloud', title: 'Sauvegarde & restauration', text: 'Snapshots sécurisés dans votre navigateur.', icon: Cloud, group: 'Données' },
  { id: 'family', title: 'Espace famille', text: 'Gérez les membres et les responsabilités du foyer.', icon: Users, group: 'Collaboration' },
  { id: 'integrations', title: 'Intégrations', text: 'Google Calendar, Outlook, Notion et Trello.', icon: PlugZap, group: 'Connexions' },
  { id: 'offline', title: 'Mode hors-ligne', text: 'LifeOS reste accessible grâce à son cache local.', icon: WifiOff, group: 'Mobilité' },
  { id: 'themes', title: 'Thèmes personnalisés', text: 'Adaptez l’accent, la densité et l’ambiance.', icon: Palette, group: 'Apparence' },
  { id: 'api', title: 'API développeurs', text: 'Générez une clé locale pour vos automatisations.', icon: Code2, group: 'Développeurs' },
  { id: 'support', title: 'Centre d’aide', text: 'Envoyez un message depuis votre espace, sans limite.', icon: LifeBuoy, group: 'Assistance' },
] as const

type FeatureId = typeof features[number]['id']
const englishFeatures: Record<FeatureId, { title: string; text: string; group: string }> = {
  ai: { title: 'Advanced AI', text: 'Contextual insights and recommendations adapted to your data.', group: 'Intelligence' },
  reports: { title: 'Automated reports', text: 'Exportable financial reviews, whenever you need them.', group: 'Data' },
  bank: { title: 'Bank sync', text: 'Local demo connector and transaction import.', group: 'Finances' },
  cloud: { title: 'Backup & restore', text: 'Secure snapshots saved in your browser.', group: 'Data' },
  family: { title: 'Family space', text: 'Manage household members and responsibilities.', group: 'Collaboration' },
  integrations: { title: 'Integrations', text: 'Google Calendar, Outlook, Notion and Trello.', group: 'Connections' },
  offline: { title: 'Offline mode', text: 'LifeOS stays available through its local cache.', group: 'Mobility' },
  themes: { title: 'Custom themes', text: 'Adjust accent, density and atmosphere.', group: 'Appearance' },
  api: { title: 'Developer API', text: 'Generate a local key for your automations.', group: 'Developers' },
  support: { title: 'Help center', text: 'Send a message from your space, without limits.', group: 'Support' },
}
export function FeaturesPage() {
  const [selected, setSelected] = useState<FeatureId>('ai'); const settings = useLifeStore(state => state.settings); const updateSettings = useLifeStore(state => state.updateSettings); const transactions = useLifeStore(state => state.transactions); const tasks = useLifeStore(state => state.tasks); const savings = useLifeStore(state => state.savings); const setChatOpen = useLifeStore(state => state.setChatOpen); const members = useLifeStore(state => state.members); const addMember = useLifeStore(state => state.addMember); const integrations = useLifeStore(state => state.integrations); const toggleIntegration = useLifeStore(state => state.toggleIntegration); const bankConnected = useLifeStore(state => state.bankConnected); const connectBank = useLifeStore(state => state.connectBank); const apiKey = useLifeStore(state => state.apiKey); const generateApiKey = useLifeStore(state => state.generateApiKey); const pushToast = useLifeStore(state => state.pushToast)
  const [memberName, setMemberName] = useState(''); const [memberRole, setMemberRole] = useState('member'); const [support, setSupport] = useState(''); const [reportFrequency, setReportFrequency] = useState('monthly')
  const t = (key: Parameters<typeof translate>[1]) => translate(settings.language, key)
  const en = settings.language === 'en'
  const l = (french: string, english: string) => en ? english : french
  const roleLabels: Record<string, string> = { member: l('Membre', 'Member'), parent: l('Parent', 'Parent'), child: l('Enfant', 'Child'), observer: l('Observateur', 'Observer'), Membre: l('Membre', 'Member'), Parent: l('Parent', 'Parent'), Enfant: l('Enfant', 'Child'), Observateur: l('Observateur', 'Observer'), Member: l('Membre', 'Member'), Child: l('Enfant', 'Child'), Observer: l('Observateur', 'Observer'), Administrateur: l('Administrateur', 'Administrator'), Administrator: l('Administrateur', 'Administrator') }
  const roleLabel = (role: string) => roleLabels[role] ?? role
  const localizedFeatures = settings.language === 'en' ? features.map(feature => ({ ...feature, ...englishFeatures[feature.id] })) : features
  const current = useMemo(() => { const now = new Date(); return transactions.filter(item => { const d = new Date(item.date); return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear() }) }, [transactions]); const income = current.filter(i => i.type === 'income').reduce((s, i) => s + i.amount, 0); const expense = current.filter(i => i.type === 'expense').reduce((s, i) => s + i.amount, 0)
  const exportReport = () => {
    const locale = en ? 'en-US' : 'fr-FR'
    const money = (value: number) => currency(value, settings.currency, settings.language, settings.hideAmounts)
    const activeTasks = tasks.filter(task => task.status !== 'done').length
    const html = `<!doctype html><meta charset="utf-8"><title>${l('Rapport LifeOS', 'LifeOS report')}</title><style>body{font:15px Inter,Arial;max-width:800px;margin:50px auto;color:#202322}h1{font-size:36px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:20px;border:1px solid #ddd;border-radius:14px}small{color:#777}strong{display:block;font-size:22px;margin-top:8px}</style><h1>${l('Rapport LifeOS', 'LifeOS report')}</h1><p>${new Date().toLocaleDateString(locale, { dateStyle: 'long' })}</p><div class="grid"><div class="card"><small>${l('Revenus', 'Income')}</small><strong>${money(income)}</strong></div><div class="card"><small>${l('Dépenses', 'Expenses')}</small><strong>${money(expense)}</strong></div><div class="card"><small>${l('Solde', 'Balance')}</small><strong>${money(income - expense)}</strong></div></div><h2>${l('Résumé', 'Summary')}</h2><p>${activeTasks} ${l('tâches actives', 'active tasks')} · ${savings.length} ${l('objectifs d’épargne', 'savings goals')}.</p>`
    downloadFile(en ? 'lifeos-report.html' : 'rapport-lifeos.html', html, 'text/html;charset=utf-8')
    pushToast({ title: l('Rapport généré', 'Report generated'), message: l('Le fichier HTML est prêt.', 'The HTML file is ready.'), tone: 'success' })
  }
  const backup = () => { const state = useLifeStore.getState(); const data = { profile: state.profile, settings: state.settings, tasks: state.tasks, notes: state.notes, habits: state.habits, journal: state.journal, goals: state.goals, events: state.events, transactions: state.transactions, budgets: state.budgets, savings: state.savings, investments: state.investments, createdAt: new Date().toISOString() }; localStorage.setItem('lifeos:manual-backup', JSON.stringify(data)); localStorage.setItem('lifeos:last-backup', new Date().toISOString()); downloadFile(en ? 'lifeos-backup.json' : 'lifeos-sauvegarde.json', JSON.stringify(data, null, 2), 'application/json'); pushToast({ title: l('Sauvegarde créée', 'Backup created'), tone: 'success' }) }
  const enableOffline = async () => { if ('serviceWorker' in navigator) { await navigator.serviceWorker.register('/sw.js'); pushToast({ title: l('Mode hors-ligne activé', 'Offline mode enabled'), message: l('Les éléments essentiels sont maintenant en cache.', 'Essential resources are now cached.'), tone: 'success' }) } }
  return <motion.div className="inner-page features-page" variants={pageTransition} initial="hidden" animate="visible" exit="exit"><section className="features-hero"><div><Badge tone="success"><Sparkles size={12} /> {t('featuresKicker')}</Badge><h1>{t('featuresTitle')}<br /><em>{t('alwaysFree')}</em></h1><p>{t('featuresSubtitle')}</p><div className="features-proof"><span><Check size={15} /> {t('fullAccess')}</span><span><Check size={15} /> {t('localData')}</span><span><Check size={15} /> {t('noCard')}</span></div></div><div className="features-orbit"><div className="orbit-core"><img src="/assets/logo.svg" alt="LifeOS" /></div>{[Bot, Cloud, Users, Palette].map((Icon, index) => <span key={index} style={{ '--i': index } as React.CSSProperties}><Icon size={20} /></span>)}</div></section><div className="section-heading"><div><span className="page-kicker">{t('advancedTools')}</span><h2>{t('everythingNeeded')}</h2><p>{t('clickFeature')}</p></div><Badge tone="success">10 {t('freeTools')}</Badge></div><motion.div className="feature-grid" variants={staggerContainer} initial="hidden" animate="visible">{localizedFeatures.map(feature => <motion.button variants={fadeInUp} key={feature.id} className={`feature-card ${selected === feature.id ? 'active' : ''}`} onClick={() => { setSelected(feature.id); window.setTimeout(() => document.getElementById('feature-workspace')?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 50) }}><span className="feature-card-icon"><feature.icon size={21} /></span><span className="free-tag">{t('free').toUpperCase()}</span><small>{feature.group}</small><strong>{feature.title}</strong><p>{feature.text}</p><span className="feature-open">{t('open')} <span>→</span></span></motion.button>)}</motion.div><section id="feature-workspace" className="feature-workspace"><header><span className="workspace-icon">{(() => { const Icon = localizedFeatures.find(f => f.id === selected)?.icon ?? Sparkles; return <Icon size={22} /> })()}</span><div><Badge tone="success">{t('includedFree')}</Badge><h2>{localizedFeatures.find(f => f.id === selected)?.title}</h2><p>{localizedFeatures.find(f => f.id === selected)?.text}</p></div></header><div className="workspace-content">
    {selected === 'ai' && <div className="ai-analysis"><div className="analysis-score"><span>{l('Score de santé financière', 'Financial health score')}</span><strong>86<small>/100</small></strong><em>{l('Très bon', 'Very good')}</em></div><div className="analysis-findings"><article><Check size={16} /><span><strong>{l('Épargne solide', 'Strong savings')}</strong><small>{l('Vous conservez', 'You retain')} {income ? Math.round((income - expense) / income * 100) : 0}% {l('de vos revenus ce mois.', 'of your income this month.')}</small></span></article><article><Sparkles size={16} /><span><strong>{l('Prochaine meilleure action', 'Next best action')}</strong><small>{l('Planifiez', 'Allocate')} {currency(1200, settings.currency, settings.language, settings.hideAmounts)} {l('vers votre fonds d’urgence.', 'to your emergency fund.')}</small></span></article><Button onClick={() => setChatOpen(true)}><Bot size={16} /> {l('Ouvrir l’assistant', 'Open assistant')}</Button></div></div>}
    {selected === 'reports' && <div className="feature-form-layout"><div><Field label={l('Fréquence du bilan', 'Report frequency')}><Select value={reportFrequency} onChange={event => setReportFrequency(event.target.value)}><option value="weekly">{l('Hebdomadaire', 'Weekly')}</option><option value="monthly">{l('Mensuel', 'Monthly')}</option><option value="quarterly">{l('Trimestriel', 'Quarterly')}</option></Select></Field><p className="helper-text">{l('Votre préférence est appliquée localement. Vous pouvez aussi générer un bilan maintenant.', 'Your preference is applied locally. You can also generate a report now.')}</p></div><div className="action-panel"><FileBarChart size={30} /><strong>{l('Rapport', 'Report')} {reportFrequency === 'weekly' ? l('hebdomadaire', 'weekly') : reportFrequency === 'quarterly' ? l('trimestriel', 'quarterly') : l('mensuel', 'monthly')}</strong><span>{l('Finances · Productivité · Objectifs', 'Finances · Productivity · Goals')}</span><Button onClick={exportReport}><Download size={16} /> {l('Générer le rapport', 'Generate report')}</Button><Button variant="secondary" onClick={() => downloadFile('transactions-lifeos.csv', toCSV(transactions as unknown as Record<string, unknown>[]), 'text/csv')}><Download size={16} /> {l('Exporter le CSV', 'Export CSV')}</Button></div></div>}
    {selected === 'bank' && <div className="connection-panel"><div className={`connection-status ${bankConnected ? 'connected' : ''}`}><Landmark size={26} /><span><strong>{bankConnected ? l('Compte démo connecté', 'Demo account connected') : l('Aucun compte connecté', 'No account connected')}</strong><small>{bankConnected ? l('Dernière synchronisation : à l’instant', 'Last synced: just now') : l('Le connecteur fonctionne en mode local et ne transmet aucune donnée.', 'The connector runs locally and does not transmit any data.')}</small></span><Badge tone={bankConnected ? 'success' : 'neutral'}>{bankConnected ? l('ACTIF', 'ACTIVE') : 'LOCAL'}</Badge></div><Button onClick={connectBank}>{bankConnected ? l('Déconnecter le compte', 'Disconnect account') : l('Connecter le compte démo', 'Connect demo account')}</Button></div>}
    {selected === 'cloud' && <div className="backup-panel"><Cloud size={36} /><h3>{l('Vos données, toujours récupérables', 'Your data, always recoverable')}</h3><p>{l('Créez un snapshot local complet et téléchargez-le immédiatement.', 'Create a complete local snapshot and download it immediately.')}</p><Button onClick={backup}><Download size={16} /> {l('Sauvegarder maintenant', 'Back up now')}</Button><small>{l('Dernière sauvegarde :', 'Last backup:')} {localStorage.getItem('lifeos:last-backup') ? new Date(localStorage.getItem('lifeos:last-backup')!).toLocaleString(en ? 'en-US' : 'fr-FR') : l('Jamais', 'Never')}</small></div>}
    {selected === 'family' && <div className="family-layout"><div className="member-list">{members.map(member => <article key={member.id}><span>{member.initials}</span><div><strong>{member.name}</strong><small>{roleLabel(member.role)}</small></div><Badge tone="success">{l('Actif', 'Active')}</Badge></article>)}</div><div className="member-form"><Field label={l('Nom', 'Name')}><Input value={memberName} onChange={event => setMemberName(event.target.value)} placeholder={l('Nom du membre', 'Member name')} /></Field><Field label={l('Rôle', 'Role')}><Select value={memberRole} onChange={event => setMemberRole(event.target.value)}><option value="member">{l('Membre', 'Member')}</option><option value="parent">{l('Parent', 'Parent')}</option><option value="child">{l('Enfant', 'Child')}</option><option value="observer">{l('Observateur', 'Observer')}</option></Select></Field><Button onClick={() => { if (memberName.trim()) { addMember(memberName.trim(), memberRole); setMemberName('') } }}><Users size={16} /> {l('Ajouter au foyer', 'Add to household')}</Button></div></div>}
    {selected === 'integrations' && <div className="integration-grid">{integrations.map(item => <article key={item.id}><span className="integration-logo">{item.name.slice(0, 1)}</span><div><strong>{item.name}</strong><small>{item.enabled ? l('Connecté localement', 'Connected locally') : l('Prêt à connecter', 'Ready to connect')}</small></div><Toggle label={`${l('Activer', 'Enable')} ${item.name}`} checked={item.enabled} onChange={() => toggleIntegration(item.id)} /></article>)}</div>}
    {selected === 'offline' && <div className="offline-panel"><WifiOff size={40} /><div><h3>{l('LifeOS partout, même sans réseau', 'LifeOS everywhere, even offline')}</h3><p>{l('Activez le service worker pour mettre en cache l’interface et vos ressources essentielles. Vos données sont déjà conservées localement.', 'Enable the service worker to cache the interface and essential resources. Your data is already stored locally.')}</p><Button onClick={enableOffline}><RefreshCw size={16} /> {l('Activer le mode hors-ligne', 'Enable offline mode')}</Button></div></div>}
    {selected === 'themes' && <div className="theme-panel"><div><h3>{l('Couleur d’accent', 'Accent color')}</h3><div className="accent-picker">{(['smoke', 'sage', 'slate', 'terracotta', 'graphite'] as const).map(accent => <button key={accent} className={`accent-${accent} ${settings.accent === accent ? 'active' : ''}`} onClick={() => updateSettings({ accent })} aria-label={accent}><Check size={14} /></button>)}</div></div><div><h3>{l('Ambiance', 'Appearance')}</h3><div className="choice-row"><button className={settings.theme === 'light' ? 'active' : ''} onClick={() => updateSettings({ theme: 'light' })}>{l('Clair', 'Light')}</button><button className={settings.theme === 'dark' ? 'active' : ''} onClick={() => updateSettings({ theme: 'dark' })}>{l('Sombre', 'Dark')}</button><button className={settings.theme === 'auto' ? 'active' : ''} onClick={() => updateSettings({ theme: 'auto' })}>{l('Auto', 'Auto')}</button></div></div></div>}
    {selected === 'api' && <div className="api-panel"><div className="code-window"><span>{l('Clé API locale', 'Local API key')}</span><code>{apiKey || l('Aucune clé générée', 'No key generated')}</code></div><div><p>{l('Cette clé sert à préparer vos automatisations locales. Elle ne donne accès à aucun serveur externe.', 'This key prepares your local automations. It does not grant access to any external server.')}</p><Button onClick={generateApiKey}><KeyRound size={16} /> {apiKey ? l('Régénérer la clé', 'Regenerate key') : l('Générer une clé', 'Generate a key')}</Button>{apiKey && <Button variant="secondary" onClick={() => navigator.clipboard.writeText(apiKey).then(() => pushToast({ title: l('Clé copiée', 'Key copied'), tone: 'success' }))}>{l('Copier', 'Copy')}</Button>}</div></div>}
    {selected === 'support' && <div className="support-panel"><div><LifeBuoy size={36} /><h3>{l('Comment pouvons-nous vous aider ?', 'How can we help?')}</h3><p>{l('Décrivez votre question ou votre idée. Le message est conservé localement dans cette démonstration.', 'Describe your question or idea. The message is stored locally in this demo.')}</p></div><div><Field label={l('Votre message', 'Your message')}><textarea className="input textarea" rows={5} value={support} onChange={event => setSupport(event.target.value)} placeholder={l('Écrivez votre message…', 'Write your message…')} /></Field><Button onClick={() => { if (support.trim()) { pushToast({ title: l('Message enregistré', 'Message saved'), message: l('Merci pour votre retour.', 'Thank you for your feedback.'), tone: 'success' }); setSupport('') } }}>{l('Envoyer le message', 'Send message')}</Button></div></div>}
  </div></section><footer className="free-manifesto"><CalendarSync size={28} /><div><strong>{l('Une seule version : la version complète.', 'One version only: the complete version.')}</strong><p>{l('LifeOS est votre propre espace. Toutes les fonctionnalités présentes ici sont accessibles gratuitement à tous les utilisateurs.', 'LifeOS is your own space. Every feature here is available to all users for free.')}</p></div></footer></motion.div>
}
