import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { LockKeyhole, ShieldCheck } from 'lucide-react'
import type { PageId } from './types'
import { useLifeStore } from './store/useLifeStore'
import { AppShell } from './components/layout/AppShell'
import { DashboardPage } from './components/pages/DashboardPage'
import { FinancePage } from './components/pages/FinancePage'
import { PersonalPage } from './components/pages/PersonalPage'
import { FeaturesPage } from './components/pages/FeaturesPage'
import { SettingsPage } from './components/pages/SettingsPage'
import { Chatbot } from './components/chatbot/Chatbot'
import { Button, Input, ToastViewport } from './components/ui/primitives'

const getPage = (): PageId => { const value = window.location.hash.replace('#/', '').split('?')[0]; if (value === 'finances' || value === 'personal' || value === 'features' || value === 'settings') return value; if (value === 'premium') return 'features'; return 'dashboard' }
export default function App() {
  const [page, setPage] = useState<PageId>(getPage); const [booting, setBooting] = useState(true); const [locked, setLocked] = useState(false); const [pin, setPin] = useState(''); const [pinError, setPinError] = useState(false)
  const settings = useLifeStore(state => state.settings); const updateSettings = useLifeStore(state => state.updateSettings); const addTask = useLifeStore(state => state.addTask); const addNote = useLifeStore(state => state.addNote); const setChatOpen = useLifeStore(state => state.setChatOpen); const en = settings.language === 'en'
  useEffect(() => { const onHash = () => setPage(getPage()); window.addEventListener('hashchange', onHash); if (!window.location.hash) window.location.hash = '#/'; const boot = window.setTimeout(() => setBooting(false), 650); const onLock = () => setLocked(true); window.addEventListener('lifeos:lock', onLock); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); return () => { window.removeEventListener('hashchange', onHash); window.removeEventListener('lifeos:lock', onLock); window.clearTimeout(boot) } }, [])
  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)')
    const apply = () => { const dark = settings.theme === 'dark' || (settings.theme === 'auto' && media.matches); document.documentElement.classList.toggle('dark', dark); document.querySelector('meta[name="theme-color"]')?.setAttribute('content', dark ? '#101210' : '#f5f6f3') }
    apply(); media.addEventListener('change', apply)
    document.documentElement.classList.toggle('reduce-motion', !settings.animations); document.documentElement.classList.toggle('parallax-enabled', settings.parallax); document.documentElement.classList.toggle('smoke-enabled', settings.smoke); document.documentElement.dataset.accent = settings.accent; document.documentElement.dataset.density = settings.density; document.documentElement.lang = settings.language
    return () => media.removeEventListener('change', apply)
  }, [settings.theme, settings.animations, settings.parallax, settings.smoke, settings.accent, settings.density, settings.language])
  const navigate = (next: PageId) => { window.location.hash = next === 'dashboard' ? '#/' : `#/${next}`; setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  useEffect(() => { const handler = (event: KeyboardEvent) => { const target = event.target as HTMLElement; const writing = ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) || target.isContentEditable; if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); (document.querySelector('.global-search input') as HTMLInputElement | null)?.focus() } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 't') { event.preventDefault(); addTask({ title: en ? 'New task' : 'Nouvelle tâche', status: 'todo', priority: 'medium', dueDate: new Date().toISOString().slice(0, 10), category: en ? 'Personal' : 'Personnel', tags: [], subtasks: [] }); navigate('personal') } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'n') { event.preventDefault(); addNote(); navigate('personal') } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'm') { event.preventDefault(); navigate('finances') } else if ((event.ctrlKey || event.metaKey) && event.key === '/') { event.preventDefault(); setChatOpen(true) } else if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 'l') { event.preventDefault(); updateSettings({ theme: settings.theme === 'dark' ? 'light' : 'dark' }) } else if ((event.ctrlKey || event.metaKey) && event.key === ',') { event.preventDefault(); navigate('settings') } else if (!writing && event.key.toLowerCase() === 'l') setLocked(true); else if (!writing && event.key.toLowerCase() === 'p') { navigate('dashboard'); window.setTimeout(() => document.getElementById('widget-pomodoro')?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 200) } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [addNote, addTask, en, setChatOpen, settings.theme, updateSettings])
  const content = useMemo(() => page === 'finances' ? <FinancePage /> : page === 'personal' ? <PersonalPage /> : page === 'features' ? <FeaturesPage /> : page === 'settings' ? <SettingsPage /> : <DashboardPage />, [page])
  if (booting) return <div className="boot-screen"><div className="boot-brand"><img src="/assets/logo.svg" alt="LifeOS" /><span><strong>LifeOS</strong><small>{en ? 'Preparing your space' : 'Préparation de votre espace'}</small></span></div><div className="boot-shell"><aside /><main><i className="skeleton hero" /><div>{Array.from({ length: 6 }, (_, i) => <i className="skeleton" key={i} />)}</div></main></div></div>
  const unlock = () => { if (!settings.pin || pin === settings.pin) { setLocked(false); setPin(''); setPinError(false) } else { setPinError(true); setPin('') } }
  return <>{settings.smoke && <div className="smoke-layer" aria-hidden="true"><i /><i /></div>}<AppShell page={page} onNavigate={navigate}><AnimatePresence mode="wait"><motion.div key={page} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>{content}</motion.div></AnimatePresence></AppShell><Chatbot /><ToastViewport /><AnimatePresence>{locked && <motion.div className="lock-screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="lock-card"><span className="lock-logo"><LockKeyhole size={28} /></span><img src="/assets/logo.svg" alt="LifeOS" /><h1>{en ? 'Welcome back' : 'Heureux de vous revoir'}</h1><p>{settings.pin ? (en ? 'Enter your PIN to return to your space.' : 'Saisissez votre code PIN pour retrouver votre espace.') : (en ? 'Your LifeOS space is locked locally.' : 'Votre espace LifeOS est verrouillé localement.')}</p>{settings.pin && <Input autoFocus type="password" inputMode="numeric" maxLength={4} value={pin} onChange={event => { setPin(event.target.value); setPinError(false) }} onKeyDown={event => event.key === 'Enter' && unlock()} placeholder="••••" className={pinError ? 'input-error pin-input' : 'pin-input'} />}{pinError && <small className="error-text">{en ? 'Incorrect PIN. Try again.' : 'Code incorrect. Réessayez.'}</small>}<Button onClick={unlock}>{settings.pin ? (en ? 'Unlock' : 'Déverrouiller') : (en ? 'Return to LifeOS' : 'Revenir à LifeOS')}</Button><span className="privacy-line"><ShieldCheck size={14} /> {en ? 'Data protected on this device' : 'Données protégées sur cet appareil'}</span></div></motion.div>}</AnimatePresence></>
}
